var Tone = {};
Tone.Loop = {};
Tone.Loop.start = function(){};
Tone.Loop.stop = function(){};
Tone.Synth = {};
Tone.Synth.toMaster = function(){};
Tone.Synth.triggerAttackRelease = function(){};
Tone.Transport = {};
Tone.Transport.start = function(){};
